defmodule Tunez.Repo.Migrations.CreateAlbums do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:album, "album_artist_id_fkey")

    alter table(:album) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "album_artist_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:album, [:artist_id])
  end

  def down do
    drop_if_exists index(:album, [:artist_id])

    drop constraint(:album, "album_artist_id_fkey")

    alter table(:album) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "album_artist_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
