defmodule Tunez.Repo.Migrations.AddUniqueAlbumNamesPerArtist do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:album, "album_artist_id_fkey")

    alter table(:album) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "album_artist_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create unique_index(:album, [:name, :artist_id],
             name: "album_unique_album_names_per_artist_index"
           )
  end

  def down do
    drop_if_exists unique_index(:album, [:name, :artist_id],
                     name: "album_unique_album_names_per_artist_index"
                   )

    drop constraint(:album, "album_artist_id_fkey")

    alter table(:album) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "album_artist_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
